using MinecraftServerManager.Models;

namespace MinecraftServerManager.Services;

public static class ClusterConfigWriter
{
    /// <summary>
    /// Writes a Velocity <c>velocity.toml</c> for the proxy instance working directory.
    /// </summary>
    public static void WriteVelocityToml(ServerInstance proxy, IReadOnlyDictionary<string, string> backendAddresses,
        string tryFirstServer)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Generated by Minecraft Server Manager — prüfen Sie die Velocity-Dokumentation.");
        sb.AppendLine("config-version = \"2.7\"");
        sb.AppendLine();
        sb.AppendLine($"bind = \"0.0.0.0:{proxy.ServerPort}\"");
        sb.AppendLine("motd = \"<#09add3>Minecraft Server Manager\"");
        sb.AppendLine("show-max-players = 500");
        sb.AppendLine("online-mode = true");
        sb.AppendLine("forwarding-secret = \"").Append(proxy.ForwardingSecret ?? "changeme").AppendLine("\"");
        sb.AppendLine("player-info-forwarding-mode = \"modern\"");
        sb.AppendLine();
        sb.AppendLine("[servers]");
        foreach (var kv in backendAddresses.OrderBy(k => k.Key))
            sb.AppendLine($"{kv.Key} = \"{kv.Value}\"");

        sb.AppendLine();
        sb.AppendLine("try = [");
        sb.AppendLine($"    \"{tryFirstServer}\"");
        sb.AppendLine("]");

        Directory.CreateDirectory(proxy.DirectoryPath);
        File.WriteAllText(Path.Combine(proxy.DirectoryPath, "velocity.toml"), sb.ToString());
    }
}
